# .github/workflows/autobot.yml

name: Autobot Posts to Instagram Twice Daily

on:
  # Schedule the workflow to run at specific times
  schedule:
    # Note: Cron times are in UTC.
    # 6:00 AM Sydney (AEDT is UTC+11) is 7:00 PM UTC on the previous day.
    - cron: '0 19 * * *'
    # 6:00 PM Sydney (AEDT is UTC+11) is 7:00 AM UTC on the same day.
    - cron: '0 7 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  post-artwork:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out your repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can change this to your preferred Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
          
      # Step 4: Run the Python script
      - name: Run the Instagram post script
        env:
          # Use the secrets you've configured in your repository settings
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        run: python scripts/autobot.py