name: Data Update

on:
  schedule:
     - cron: '12 0 * * 5'   # Friday 1200 UTC, 11/12 pm Syd
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run data update script
        run: python scripts/metfetch.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/artworkids.json public/metadata public/images
          git diff --quiet || git commit -m "Automated data update"
          git push
